# This is a basic workflow to help you get started with Actions

name: Run pytest

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Pythonの環境をセットアップ
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # PYTHONPATHのセット
      - name: Set python path
        run: |
          export PYTHONPATH="/home/runner/work/study_pytest/study_pytest/:$PYTHONPATH"

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          pytest
        continue-on-error: true

      # # テスト結果の表示
      # - name: Upload Unit Test Results
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Unit Test Results (Python 3.7)
      #     path: results/*.xml

      # - name: Download Artifacts
      #   if: success() || failure()
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts

      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   with:
      #     files: artifacts/**/*.xml
